Fix vault-init not closing connection to vault server
kelseyhightower/vault-init pull request #12
Opened 2018-12-05 02:24 UTC by gburiola

vault-init is not closing the connection to the vault-server:

```
tcp        0      0 127.0.0.1:59604         127.0.0.1:8200          ESTABLISHED 368/vault-init
tcp        0      0 127.0.0.1:59580         127.0.0.1:8200          ESTABLISHED 368/vault-init
tcp        0      0 127.0.0.1:59626         127.0.0.1:8200          ESTABLISHED 368/vault-init
tcp        0      0 127.0.0.1:59618         127.0.0.1:8200          ESTABLISHED 368/vault-init
tcp        0      0 127.0.0.1:59592         127.0.0.1:8200          ESTABLISHED 368/vault-init
```

2018-12-05 02:27 UTC, gburiola commented on main.go
> -		if response != nil && response.Body != nil {
`response.Body` will always be `nil` because the request above is `HEAD`.
Because of that we never enter this `if` block and never run `response.Body.Close()`

2018-12-05 02:27 UTC, gburiola commented on main.go
> +		IdleConnTimeout: 300 * time.Second,
this is not strictly necessary but a safety mechanism in case connection is accidentally left open.

2018-12-05 14:53 UTC, gruzewski commented on main.go
> -		if response != nil && response.Body != nil {
You can actually move it down the file and outside the "if" statement. Checking the error is enough to confirm that response is not nil:
```
func (c *Client) Head(url string) (resp *Response, err error) {
	req, err := NewRequest("HEAD", url, nil)
	if err != nil {
		return nil, err
	}
	return c.Do(req)
}
```
So the code would like this:
```
if err != nil {
	log.Println(err)
	time.Sleep(checkIntervalDuration)
	continue
}

defer response.Body.Close()
```

2018-12-06 20:16 UTC, sethvargo requested changes

2018-12-06 20:16 UTC, sethvargo commented on main.go
> +		IdleConnTimeout: 300 * time.Second,
This should be in the Transport struct

2018-12-06 20:16 UTC, sethvargo commented on main.go
> -		if response != nil && response.Body != nil {
I'm not sure I understand. If `request.Body` is nil, it's not safe to call `response.Body.Close()`. You can't close a body that doesn't exist.

2018-12-06 20:51 UTC, gruzewski commented on main.go
> -		if response != nil && response.Body != nil {
That's true. But that part is covered by checking `err`. 

If `response.Body` is nil, it means `err` is not nil and you will execute whatever is in the `if` statement (basically skipping this iteration and not executing `defer response.Body.Close()`).

2018-12-06 22:22 UTC, gburiola commented on main.go
> +		IdleConnTimeout: 300 * time.Second,
Thanks for catching that.

Fixedd.

2018-12-06 23:02 UTC, sethvargo requested changes

2018-12-06 23:02 UTC, sethvargo commented on main.go
> -		if response != nil && response.Body != nil {
There is no guarantee that there's a body. You're saying that there's a case where there's a response body with an error?

The flow is currently this:

```text
HEAD req
if response.body, close
if err, continue
```

I don't understand how this code is performing differently than the expected behavior.

2018-12-07 00:09 UTC, gburiola commented
forget this.

we were using `gcr.io/hightowerlabs/vault-init:latest` and it seems like that hasn't been updated since 24 Apr 2018.

The memory leak has already been fixed on 3e0c4f35.
 

2018-12-07 00:09 UTC, closed without merging

2018-12-07 14:19 UTC, sethvargo commented
You can use `sethvargo/vault-init` which will track master. It's also updated to support Vault 1.0 auto-unsealing.

2018-12-08 12:09 UTC, gruzewski commented on main.go
> -		if response != nil && response.Body != nil {
So `defer` wouldn't work as it is a loop. My fault. Remaining bits are following the example from golang's page https://golang.org/pkg/net/http/ Also, in the comment of `response.Head` you can read:
```
// The http Client and Transport guarantee that Body is always
// non-nil, even on responses without a body or responses with
// a zero-length body. It is the caller's responsibility to
// close Body.
```
Anyway, Luis has already close this PR. Thanks for the help :)